a = "  Abdul Jabbar  "
a.capitalize()
a.casefold()
a.count(a)
a.encode()
a.endswith("r")
a.expandtabs()
a.find("d")
print(a.strip())
a = "     we are pakistani and we love our country"
a.find("pakistani")
a.index("ar")
a.isalnum()
a.isascii()
a.isdecimal()
a.isdigit()
a.isidentifier()
a.islower()
a.isnumeric()
a.isprintable()
a.isspace()
a.istitle()
a.isupper()
a.join("acd")
a.ljust(100)
a.lower()
a.lstrip()
a.partition("a")
a.replace("country", "country and land")
a.rfind("and")
a.rindex("and")
("abbdabdb      ").rjust(20)
a.rpartition("a")
a.rsplit()
a.rstrip()
a.split()
a.startswith(" ")
a.strip()
a.swapcase()
a.title()
a.upper()
a.zfill(2)